# ---------------------------------------------------- #
# Note: this file originates in template-action-node #
# ---------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

permissions: read-all

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-action-node.yml@master
    secrets: inherit
    permissions:
      contents: write
      statuses: write
      packages: write
      pull-requests: write
